# Generated by Django 4.1.6 on 2023-02-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'pv'), (2, 'group'), (3, 'channel'), (4, 'bot')])),
            ],
        ),
    ]
