# Generated by Django 4.1.6 on 2023-02-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_profile_image_account_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
